import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/startpage">StartPage</Link>
        </li>
        <li>
          <Link to="/cookies">Cookies</Link>
        </li>
        <li>
          <Link to="/signup">SignUp</Link>
        </li>
        <li>
          <Link to="/intropage">IntroPage</Link>
        </li>
        <li>
          <Link to="/fromdropdown">FromDropdown</Link>
        </li>
        <li>
          <Link to="/topop">ToPOP</Link>
        </li>
        <li>
          <Link to="/calenderpop">CalenderPOP</Link>
        </li>
        <li>
          <Link to="/dateselect">Dateselect</Link>
        </li>
        <li>
          <Link to="/noofpeople">NoofPeople</Link>
        </li>
        <li>
          <Link to="/returningfltview">ReturningFltview</Link>
        </li>
        <li>
          <Link to="/hoverreturningflt">HoverReturningFlt</Link>
        </li>
        <li>
          <Link to="/returningflightsoptions">ReturningFlightsoptions</Link>
        </li>
        <li>
          <Link to="/returningflightsel">ReturningFlightSel</Link>
        </li>
        <li>
          <Link to="/passengerinfo">PassengerInfo</Link>
        </li>
        <li>
          <Link to="/passengerinfodata">PassengerInfoData</Link>
        </li>
        <li>
          <Link to="/seatselection">SeatSelection</Link>
        </li>
        <li>
          <Link to="/seatselection1">SeatSelection1</Link>
        </li>
        <li>
          <Link to="/seatselection2">SeatSelection2</Link>
        </li>
        <li>
          <Link to="/upgradseat">UpgradSeat</Link>
        </li>
        <li>
          <Link to="/seatspecification">SeatSpecification</Link>
        </li>
        <li>
          <Link to="/creditcardpayment">CreditCardPayment</Link>
        </li>
        <li>
          <Link to="/paymentwithdata">PaymentwithData</Link>
        </li>
        <li>
          <Link to="/bookretuuringfligh">BookRetuuringFligh</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
